[build]
  Command = "npm run build:api"
  Functions = "lambda"
  Publish = "build"

[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "app/"